### ISSUE TITLE
FindGLUT.cmake doesn't work with static library

### ISSUE THREAD

**Issue by davemc0** [FreeGLUTProject/freeglut#99] opened 2022-03-30 01:43 UTC
FindGLUT.cmake seems to be somewhere between underpowered and buggy. Its biggest bug is that it just doesn't work with static libraries, at least not on Windows. It can't find freeglut_static.lib. 

I think if it were patterned after findGLEW.cmake it would be much more robust.

I'm happy to work on improving this if I can get some guidance and consensus on the direction to go in. I don't even know the process for getting fixes to findGLUT.cmake pushed back to the CMake distro.

[Sorry if this isn't the ideal forum to raise this issue, but the developers of some other projects support their respective find*.cmake files, so I thought I'd give it a shot.]

**Comment by jtsiomb** [comment] 2022-03-30 08:59
Sounds great. If you're willing to get involved and improve findglut.cmake, please do.

But as that file is (I guess) part of cmake, I don't see what we can do about it. As you said, this is probably not the best place to raise this issue. You should talk to the cmake developers about it.

As this is not a bug in freeglut, I'm closing the issue. But feel free to keep talking about it here, if you think there's anything we can do to help.

**Closed by jtsiomb** 2022-03-30 08:59 UTC

**Comment by davemc0** [comment] 2022-03-30 20:17
Fair enough.

My questions for this group would be:
* Where and how do you install your FreeGLUT on Windows?
* Do you use the static or dynamic library after installation?
* How do you find FreeGLUT in CMake?

* Where is CMake hosted? Any guidance on how to submit improvements for it?

**Comment by jtsiomb** [comment] 2022-03-30 20:26
I'm not a windows user, and I'm also not a cmake user, so I can't really answer most of these questions.

I use GNU/Linux, and GNU make. On GNU/Linux, as is the case with pretty much all UNIX systems in general, libraries and header files are installed in standard paths, so there's no need to "find" them. To use freeglut on a UNIX system, it suffices to `#include <GL/glut.h>` (or `GL/freeglut.h`) and link with `-lglut`.

For the cmake project and how to contribute to it, a quick google search led me to this: https://cmake.org/get-involved/
