### ISSUE TITLE
Compile error while building fg_spaceball_mswin.c with MinGW gcc on Windows

### ISSUE THREAD

**Issue by Fun-User** [FreeGLUTProject/freeglut#143] opened 2023-08-07 13:33 UTC
Following the instructions [here](https://github.com/FreeGLUTProject/freeglut/blob/master/README.cmake) to build with CMake on windows using MingGW's gcc/g++. Everything works until I try to 'make' the project where it fails on fg_spaceball_mswin.c with the following error.

```
[ 22%] Building C object CMakeFiles/freeglut.dir/src/mswin/fg_spaceball_mswin.c.obj
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c: In function 'fgSpaceballHandleWinEvent':
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:155:45: error: subscripted value is neither array nor pointer nor vector
             if (pRawInput->data.hid.bRawData[0] ==
                                             ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:158:71: error: subscripted value is neither array nor pointer nor vector
                 short* pnData = (short*)(&pRawInput->data.hid.bRawData[1]);
                                                                       ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:164:50: error: subscripted value is neither array nor pointer nor vector
             else if (pRawInput->data.hid.bRawData[0] ==
                                                  ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:167:71: error: subscripted value is neither array nor pointer nor vector
                 short* pnData = (short*)(&pRawInput->data.hid.bRawData[1]);
                                                                       ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:173:50: error: subscripted value is neither array nor pointer nor vector
             else if (pRawInput->data.hid.bRawData[0] ==
                                                  ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:176:91: error: subscripted value is neither array nor pointer nor vector
                 unsigned long dwKeystate = *(unsigned long*)(&pRawInput->data.hid.bRawData[1]);
                                                                                           ^
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:177:30: warning: unused variable 'state' [-Wunused-variable]
                 unsigned int state = GLUT_UP;
                              ^~~~~
C:\Users\User\Projects\shaders\lib\freeglut-3.4.0\src\mswin\fg_spaceball_mswin.c:109:10: warning: unused variable 'inputCode' [-Wunused-variable]
     UINT inputCode = (UINT)wParam;
          ^~~~~~~~~
CMakeFiles\freeglut.dir\build.make:570: recipe for target 'CMakeFiles/freeglut.dir/src/mswin/fg_spaceball_mswin.c.obj' failed
mingw32-make[2]: *** [CMakeFiles/freeglut.dir/src/mswin/fg_spaceball_mswin.c.obj] Error 1
CMakeFiles\Makefile2:151: recipe for target 'CMakeFiles/freeglut.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/freeglut.dir/all] Error 2
Makefile:134: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

gcc version
```
User@DESKTOP-B89R2NG MINGW64 ~/Projects/shaders/lib/freeglut-3.4.0/build (master)
$ which gcc
/c/MinGW/bin/gcc

User@DESKTOP-B89R2NG MINGW64 ~/Projects/shaders/lib/freeglut-3.4.0/build (master)
$ gcc --version
gcc.exe (MinGW.org GCC-8.2.0-3) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I am not familiar with coding on Windows, but to myself the code does not appear to have an obvious bug. Wondering if anyone else was able to compile with CMake and MinGW?

**Comment by jtsiomb** [comment] 2023-08-07 21:11
I don't have a windows machine to test, but the automated mingw build is currently passing, you can check the steps it takes here, if it helps: https://github.com/FreeGLUTProject/freeglut/blob/master/.github/workflows/build_win_mingw.yml

**Comment by blitzcoder** [comment] 2023-09-30 23:16
@Fun-User  Try using a higher version, tested to build all on MinGW 10.x

**Comment by xavierholt** [comment] 2023-11-28 04:24
This looks like a duplicate of #93.  The solutions listed there are to either:
- Compile with MSVC instead of GCC, or...
- Find the `winuser.h` header file that's getting included, and manually edit it (!?!?) to make the [`RAWHID`struct's](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawhid) `bRawData` member be a byte array of size one rather than a byte.

**Comment by jtsiomb** [comment] 2023-11-28 07:56
GCC certainly works, and according to my past self in that linked issue, my copy came with the correct version of winuser.

Anyway if this issue keeps coming up, maybe it's worth working around it by defining our own version of RAWHID... I'll try it later.

**Comment by jtsiomb** [comment] 2023-11-28 08:17
Commited a workaround, can you test and let us know if it solves the issue?

**Comment by xavierholt** [comment] 2023-11-28 08:40
Thanks for the super-fast response!  I'm actually helping someone else with the install, so I can't test this myself, but I'll try to have a report for you by tomorrow.

**Comment by xavierholt** [comment] 2023-11-29 05:43
@jtsiomb - That fixed almost everything, but there's one more use of the other struct on [line 172](https://github.com/FreeGLUTProject/freeglut/blob/master/src/mswin/fg_spaceball_mswin.c#L172C41-L172C41).

In the meantime, we edited the buggy `winuser.h` file and were able to compile with GCC just fine afterwards.  The bad header seems to come as part of MinGW (not MinGW-w64, which has the correct definition):

```c
typedef struct tagRAWHID
{ DWORD 			dwSizeHid;
  DWORD 			dwCount;
  BYTE				bRawData;
} RAWHID, *PRAWHID, *LPRAWHID;
```

I'll try to file a bug with them if I can access [their website](https://osdn.net/projects/mingw/), but I'm getting Bad Gateway errors for now...

**Comment by jtsiomb** [comment] 2023-11-29 09:54
ok, just fixed that one too. Thanks for testing.

**Closed by jtsiomb** 2023-11-29 09:54 UTC

**Comment by xavierholt** [comment] 2023-11-29 18:42
No problem at all - thanks for helping out!
