### ISSUE TITLE
Build error at fg_spaceball_mswin.c.obj

### ISSUE THREAD

**Issue by lin71008** [FreeGLUTProject/freeglut#93] opened 2021-10-20 12:36 UTC
* OS: Windows 10
* FreeGLUT version: 3.2.1
* Compiler: gcc version 9.2.0 (MinGW.org GCC Build-2)

```
...
[ 26%] Building C object CMakeFiles/freeglut.dir/src/mswin/fg_spaceball_mswin.c.
obj
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c: In function 'fgSpaceball
HandleWinEvent':
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:155:45: error: subscripte
d value is neither array nor pointer nor vector
  155 |             if (pRawInput->data.hid.bRawData[0] ==
      |                                             ^
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:158:71: error: subscripte
d value is neither array nor pointer nor vector
  158 |                 short* pnData = (short*)(&pRawInput->data.hid.bRawData[1
]);
      |                                                                       ^
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:164:50: error: subscripte
d value is neither array nor pointer nor vector
  164 |             else if (pRawInput->data.hid.bRawData[0] ==
      |                                                  ^
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:167:71: error: subscripte
d value is neither array nor pointer nor vector
  167 |                 short* pnData = (short*)(&pRawInput->data.hid.bRawData[1
]);
      |
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:173:50: error: subscripte
d value is neither array nor pointer nor vector
  173 |             else if (pRawInput->data.hid.bRawData[0] ==
      |                                                  ^
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:176:91: error: subscripte
d value is neither array nor pointer nor vector
  176 |                 unsigned long dwKeystate = *(unsigned long*)(&pRawInput-
>data.hid.bRawData[1]);
      |
                  ^
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:177:30: warning: unused v
ariable 'state' [-Wunused-variable]
  177 |                 unsigned int state = GLUT_UP;
      |                              ^~~~~
C:\MinGW\freeglut-3.2.1\src\mswin\fg_spaceball_mswin.c:109:10: warning: unused v
ariable 'inputCode' [-Wunused-variable]
  109 |     UINT inputCode = (UINT)wParam;
      |          ^~~~~~~~~
make[2]: *** [CMakeFiles/freeglut.dir/src/mswin/fg_spaceball_mswin.c.obj] Error
1
make[1]: *** [CMakeFiles/freeglut.dir/all] Error 2
make: *** [all] Error 2

```

Hmm... how can i fix it.

**Comment by lin71008** [comment] 2021-10-20 14:45
And... if I use MSVC instead of MinGW, everything will work perfectly... 
Am I set it wroung...

Cmake command:
`cmake -S . -B "ms-build" -G "Visual Studio 16 2019"` and `cmake -S . -B "mgw-build" -G "MinGW Makefiles"`

**Comment by jtsiomb** [comment] 2022-03-01 19:23
First disclaimer: this is not the official freeglut repo. So (as you may have noticed), your bug report here might easily go unnoticed for a long time. The official repo and bug tracker is hosted on sourceforge.

Second disclaimer: I'm not the right person to respond to any windows related issues.

Having said that, my copy of the windows headers (winuser.h) which comes with the mingw cross-compiler package on Debian, seems to include a definition of the `RAWHID` structure, where `bRawData` is certainly an array, so that error message doesn't make any sense. Can you locate your winuser.h file and see how the `bRawData` field of `RAWHID` is defined?

**Comment by Fengzi2333** [comment] 2022-04-08 07:00
run into the same issue, thanks for  @jtsiomb
here is the solution:
search your winuser.h to find the defination of tagRAWHID, it will be like this:
`  typedef struct tagRAWHID {
    DWORD dwSizeHid;
    DWORD dwCount;
    BYTE bRawData;
  } RAWHID,*PRAWHID,*LPRAWHID;`
then modify it to 
`  typedef struct tagRAWHID {
    DWORD dwSizeHid;
    DWORD dwCount;
    BYTE bRawData[1];
  } RAWHID,*PRAWHID,*LPRAWHID;`

**Comment by jtsiomb** [comment] 2022-04-08 12:23
Ok I have a windows machine, with multiple compilers and IDEs installed, so I did a survey. I did a search for all the installed versions of `winuser.h` and looked to see how they define their `RAWHID` structure and its `bRawData` field.

Specifically I found winuser.h files the following directories in my system.
    - `C:\msys64\usr\include\w32api` (msys2)
    - `C:\msys64\mingw32\i686-w64-mingw32\include` (msys2/mingw32)
    - `C:\WATCOM\h\nt` (OpenWatcom 2.0)
    - `C:\Program Files (x86)\Microsoft Visual Studio\VC98\Include` (MS Visual C++ 6.0)
    - `C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\Include` (MS Visual Studio 2005)
    - `C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include`
    - `C:\Program Files (x86)\Windows Kits\8.1\Include\um`
    - `C:\Program Files (x86)\Windows Kits\10\Include\<version number>\um` multiples of this, where `<version number>` is: 10.0.15063.0, 10.0.17763.0, 10.0.18362.0, and 10.0.20348.0.

Out of these, the MSVC6 winuser.h did not contain a RAWHID structure at all, and *all* the rest had their `bRawData` field defined as `BYTE bRawData[1]`.

This leads me to believe that this is not a compatibility issue with some windows compilers that needs to be handled by freeglut, but rather someone at some point distributed an incorrect version of winuser.h, and anyone with this problem should go ahead and fix their RAWHID structure as @Fengzi2333 suggested.

In any case it's not a bug in freeglut, so I'm closing this.

**Closed by jtsiomb** 2022-04-08 12:23 UTC
